FROM python:3.10.20-alpine3.23 AS builder
WORKDIR /app
COPY *.py .
COPY requirements.txt .
RUN pip3 install -r requirements.txt


FROM python:3.10.20-alpine3.23
WORKDIR /app
COPY --from=builder /app /app
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop
RUN chown -R roboshop:roboshop /app
RUN user roboshop
CMD ["uwsgi" ,"--ini"]
ENTRYPOINT ["payment.ini"]



# FROM python:3
# WORKDIR /app
# COPY payment.ini .
# COPY *.py .
# COPY requirements.txt .
# RUN pip3 install -r requirements.txt
# CMD ["uwsgi","--ini","payment.ini"]