FROM python:3.10.20-alpine3.23 AS builder
WORKDIR /app
# Install build dependencies as we are using alpine image which doesnot include them
RUN apk add --no-cache \
    gcc \
    musl-dev \
    python3-dev \
    libffi-dev
COPY *.py .
COPY requirements.txt .
RUN pip3 install -r requirements.txt


FROM python:3.10.20-alpine3.23
WORKDIR /app
COPY --from=builder /app /app
RUN groupadd -S roboshop && useradd -S roboshop -G roboshop
RUN chown -R roboshop:roboshop /app
USER roboshop
ENTRYPOINT ["uwsgi" ,"--ini"]
CMD ["payment.ini"]



# FROM python:3
# WORKDIR /app
# COPY payment.ini .
# COPY *.py .
# COPY requirements.txt .
# RUN pip3 install -r requirements.txt
# CMD ["uwsgi","--ini","payment.ini"]