FROM  node:20.20.2-alpine3.23 AS builder
WORKDIR /app
COPY *.js .
COPY package.json .
RUN npm install 

FROM node:20.20.2-alpine3.23
WORKDIR /app
COPY --from=builder /app /app
ENV REDIS_HOST=redis \
    CATALOGUE_HOST=catalogue \
    CATALOGUE_PORT=8080
RUN groupadd -S roboshop && useradd -S roboshop -G roboshop
RUN chown -R roboshop:roboshop /app
RUN user roboshop
CMD ["node"]
ENTRYPOINT ["server.js"]



# FROM node:20
# WORKDIR app
# COPY package.json .
# COPY *.js .
# RUN npm install
# ENV REDIS_HOST="redis" \
#     CATALOGUE_HOST="catalogue" \
#     CATALOGUE_PORT="8080"
# CMD ["node","server.js"]